# permissions for end users to view dbaasfeatureflags.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dbaasfeatureflag-viewer-role
rules:
- apiGroups:
  - dbaas.redhat.com
  resources:
  - dbaasfeatureflags
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dbaas.redhat.com
  resources:
  - dbaasfeatureflags/status
  verbs:
  - get
