# permissions for end users to edit dbaasfeatureflags.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dbaasfeatureflag-editor-role
rules:
- apiGroups:
  - dbaas.redhat.com
  resources:
  - dbaasfeatureflags
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dbaas.redhat.com
  resources:
  - dbaasfeatureflags/status
  verbs:
  - get
