apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: dbaas-operator
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/myeung/dbaas-operator-catalog:v0.4.0
  displayName: DBaaS Operator
